import type { Metadata } from "next";
import "../../../globals.css";
import DashNav from "./dash_nav";
import Sidebar from "./side";
import localFont from "next/font/local";
const geistSans = localFont({
  src: "../../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#081028]`}>
      <DashNav />
      <div className="flex justify-between">
        <div className="w-1/5">
          <Sidebar />
        </div>
        <div className="w-full">{children}</div>
      </div>
    </main>
  );
}
